name: 'Install'
description: 'Set up and install dependencies'

inputs:
  fetch-depth:
    description: 'Number of commits to fetch'
    default: '1'
    required: false
  persist-credentials:
    description: 'Whether to persist credentials'
    default: 'true'
    required: false

runs:
  using: composite
  steps:
    - name: Check out
      uses: actions/checkout@v3

    - name: Setup pnpm
      uses: pnpm/action-setup@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: pnpm
        registry-url: 'https://registry.npmjs.org'

    - name: Use Latest Corepack
      run: |
        echo "Before: corepack version => $(corepack --version || echo 'not installed')"
        npm install -g corepack@latest
        echo "After : corepack version => $(corepack --version)"
        corepack enable
        pnpm --version
        
    - name: Install Dependencies
      shell: bash
      run: |
        corepack enable
        pnpm install
        pnpm build
        cd example
        pnpm install
        cd ../next-example
        pnpm install
