import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from "./provider";
import { countStore } from "./useCount";
import { getCount } from "./api";
// import ServerProvider from "./server-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const count = await getCount();
  const [, setCount] = countStore.use();
  setCount(state => ({ ...state, count }))

  return (
    <Provider count={{ count }}>
      {/* <ServerProvider count={{ count }}> */}
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
      {/* </ServerProvider> */}
    </Provider>
  );
}
